/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AziendaIndexRouteImport } from './routes/azienda.index'
import { Route as GestioneSinistriDaGrandineIndexRouteImport } from './routes/gestione-sinistri-da-grandine.index'
import { Route as LevabolliRiparazioneAutoGrandinateIndexRouteImport } from './routes/levabolli-riparazione-auto-grandinate.index'
import { Route as PellicolePerVetriIndexRouteImport } from './routes/pellicole-per-vetri.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AziendaIndexRoute = AziendaIndexRouteImport.update({
  id: '/azienda/',
  path: '/azienda/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestioneSinistriDaGrandineIndexRoute =
  GestioneSinistriDaGrandineIndexRouteImport.update({
    id: '/gestione-sinistri-da-grandine/',
    path: '/gestione-sinistri-da-grandine/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LevabolliRiparazioneAutoGrandinateIndexRoute =
  LevabolliRiparazioneAutoGrandinateIndexRouteImport.update({
    id: '/levabolli-riparazione-auto-grandinate/',
    path: '/levabolli-riparazione-auto-grandinate/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PellicolePerVetriIndexRoute = PellicolePerVetriIndexRouteImport.update({
  id: '/pellicole-per-vetri/',
  path: '/pellicole-per-vetri/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azienda/': typeof AziendaIndexRoute
  '/gestione-sinistri-da-grandine/': typeof GestioneSinistriDaGrandineIndexRoute
  '/levabolli-riparazione-auto-grandinate/': typeof LevabolliRiparazioneAutoGrandinateIndexRoute
  '/pellicole-per-vetri/': typeof PellicolePerVetriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azienda': typeof AziendaIndexRoute
  '/gestione-sinistri-da-grandine': typeof GestioneSinistriDaGrandineIndexRoute
  '/levabolli-riparazione-auto-grandinate': typeof LevabolliRiparazioneAutoGrandinateIndexRoute
  '/pellicole-per-vetri': typeof PellicolePerVetriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azienda/': typeof AziendaIndexRoute
  '/gestione-sinistri-da-grandine/': typeof GestioneSinistriDaGrandineIndexRoute
  '/levabolli-riparazione-auto-grandinate/': typeof LevabolliRiparazioneAutoGrandinateIndexRoute
  '/pellicole-per-vetri/': typeof PellicolePerVetriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/azienda/'
    | '/gestione-sinistri-da-grandine/'
    | '/levabolli-riparazione-auto-grandinate/'
    | '/pellicole-per-vetri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/azienda'
    | '/gestione-sinistri-da-grandine'
    | '/levabolli-riparazione-auto-grandinate'
    | '/pellicole-per-vetri'
  id:
    | '__root__'
    | '/'
    | '/azienda/'
    | '/gestione-sinistri-da-grandine/'
    | '/levabolli-riparazione-auto-grandinate/'
    | '/pellicole-per-vetri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AziendaIndexRoute: typeof AziendaIndexRoute
  GestioneSinistriDaGrandineIndexRoute: typeof GestioneSinistriDaGrandineIndexRoute
  LevabolliRiparazioneAutoGrandinateIndexRoute: typeof LevabolliRiparazioneAutoGrandinateIndexRoute
  PellicolePerVetriIndexRoute: typeof PellicolePerVetriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azienda/': {
      id: '/azienda/'
      path: '/azienda'
      fullPath: '/azienda/'
      preLoaderRoute: typeof AziendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestione-sinistri-da-grandine/': {
      id: '/gestione-sinistri-da-grandine/'
      path: '/gestione-sinistri-da-grandine'
      fullPath: '/gestione-sinistri-da-grandine/'
      preLoaderRoute: typeof GestioneSinistriDaGrandineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levabolli-riparazione-auto-grandinate/': {
      id: '/levabolli-riparazione-auto-grandinate/'
      path: '/levabolli-riparazione-auto-grandinate'
      fullPath: '/levabolli-riparazione-auto-grandinate/'
      preLoaderRoute: typeof LevabolliRiparazioneAutoGrandinateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pellicole-per-vetri/': {
      id: '/pellicole-per-vetri/'
      path: '/pellicole-per-vetri'
      fullPath: '/pellicole-per-vetri/'
      preLoaderRoute: typeof PellicolePerVetriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AziendaIndexRoute: AziendaIndexRoute,
  GestioneSinistriDaGrandineIndexRoute: GestioneSinistriDaGrandineIndexRoute,
  LevabolliRiparazioneAutoGrandinateIndexRoute:
    LevabolliRiparazioneAutoGrandinateIndexRoute,
  PellicolePerVetriIndexRoute: PellicolePerVetriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
